server:
  port: 9000

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_registration
    username: root
    password: Yash@1998
  jpa:
    show-sql: true